name: XSS CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Установка Docker и Docker Compose
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Проверка версий
      - name: Verify tools
        run: |
          docker --version
          docker-compose --version

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

